Import Packages

In [69]:
import pandas as pd
import numpy as np

Import raw data from Marks file:

In [70]:
sslc = pd.read_csv('marks.txt', sep = ';',header = None, index_col = None)

<ipython-input-70-71152839110a>:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  sslc = pd.read_csv('marks.txt', sep = ';',header = None, index_col = None)

In [71]:
print(type(sslc))

<class 'pandas.core.frame.DataFrame'>

In [72]:
sslc.head(10)

  0      1    2    3   4   5   6    7    8    9   10
0  A  10001  053  036  28  16  44  177  NaN  NaN NaN
1  A  10002  058  037  42  35  40  212    P  NaN NaN
2  A  10003  072  056  71  55  70  324    P  NaN NaN
3  A  10004  087  064  83  58  65  357    P  NaN NaN
4  A  10005  059  045  50  35  48  237    P  NaN NaN
5  A  10006  044  037  25  18  37  161  NaN  NaN NaN
6  A  10007  062  046  49  36  44  237    P  NaN NaN
7  A  10008  087  071  97  71  81  407    P  NaN NaN
8  A  10009  043  040  45  35  35  198    P  NaN NaN
9  A  10010  049  042  20  27  40  178  NaN  NaN NaN

In [73]:
sslc.size

2042337

In [74]:
sslc.count()

0     185667
1     185667
2     185667
3     185667
4     185667
5     185667
6     185667
7     185667
8     159072
9        113
10         0
dtype: int64

In [75]:
sslc.shape

(185667, 11)

In [76]:
sslc.ndim

2

In [77]:
sslc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185667 entries, 0 to 185666
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       185667 non-null  object
 1   1       185667 non-null  int64
 2   2       185667 non-null  object
 3   3       185667 non-null  object
 4   4       185667 non-null  object
 5   5       185667 non-null  object
 6   6       185667 non-null  object
 7   7       185667 non-null  object
 8   8       159072 non-null  object
 9   9       113 non-null     object
 10  10      0 non-null       float64
dtypes: float64(1), int64(1), object(9)
memory usage: 15.6+ MB

In [78]:
sslc.nunique()

0          6
1     185667
2         96
3         95
4         99
5         98
6         97
7        882
8          1
9          1
10         0
dtype: int64

In [79]:
round(sslc.describe())

             1    10
count  185667.0  0.0
mean   105015.0  NaN
std     54921.0  NaN
min     10001.0  NaN
25%     57314.0  NaN
50%    105291.0  NaN
75%    152582.0  NaN
max    199999.0  NaN

In [80]:
sslc.describe(include = [object])

             0       2       3       4       5       6       7       8    9
count   185667  185667  185667  185667  185667  185667  185667  159072  113
unique       6      96      95      99      98      97     882       1    1
top          B     085     035      35      35      35     278       P    W
freq     41341    5989    6703   12842   25723    5334     592  159072  113

In [81]:
sslc.describe(exclude = [object])

                  1    10
count  185667.000000  0.0
mean   105014.949043  NaN
std     54921.152696  NaN
min     10001.000000  NaN
25%     57314.500000  NaN
50%    105291.000000  NaN
75%    152581.500000  NaN
max    199999.000000  NaN

In [82]:
sslc.describe(include = 'all')

,0,1,2,3,4,5,6,7,8,9,10
count,185667,185667.000000,185667,185667,185667,185667,185667,185667.0,159072,113,0.0
unique,6,NaN,96,95,99,98,97,882.0,1,1,NaN
top,B,NaN,085,035,35,35,35,278.0,P,W,NaN
freq,41341,NaN,5989,6703,12842,25723,5334,592.0,159072,113,NaN
mean,NaN,105014.949043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,54921.152696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,10001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,57314.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,105291.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,152581.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,199999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
sslc.memory_usage()

Index        128
0        1485336
1        1485336
2        1485336
3        1485336
4        1485336
5        1485336
6        1485336
7        1485336
8        1485336
9        1485336
10       1485336
dtype: int64

In [84]:
sslc.columns = ['Region','Roll_no','fl','sl','math','sci','sst','total','pass','withheld','extra']

In [85]:
sslc.head()

  Region  Roll_no   fl   sl math sci sst total pass withheld  extra
0      A    10001  053  036   28  16  44   177  NaN      NaN    NaN
1      A    10002  058  037   42  35  40   212    P      NaN    NaN
2      A    10003  072  056   71  55  70   324    P      NaN    NaN
3      A    10004  087  064   83  58  65   357    P      NaN    NaN
4      A    10005  059  045   50  35  48   237    P      NaN    NaN

In [86]:
sslc['pass']

0         NaN
1           P
2           P
3           P
4           P
         ...
185662    NaN
185663    NaN
185664    NaN
185665    NaN
185666    NaN
Name: pass, Length: 185667, dtype: object

In [87]:
sslc.iloc[1:6]

  Region  Roll_no   fl   sl math sci sst total pass withheld  extra
1      A    10002  058  037   42  35  40   212    P      NaN    NaN
2      A    10003  072  056   71  55  70   324    P      NaN    NaN
3      A    10004  087  064   83  58  65   357    P      NaN    NaN
4      A    10005  059  045   50  35  48   237    P      NaN    NaN
5      A    10006  044  037   25  18  37   161  NaN      NaN    NaN

In [88]:
sslc.set_index('Roll_no', inplace = True)

In [89]:
sslc.head()

        Region   fl   sl math sci sst total pass withheld  extra
Roll_no
10001        A  053  036   28  16  44   177  NaN      NaN    NaN
10002        A  058  037   42  35  40   212    P      NaN    NaN
10003        A  072  056   71  55  70   324    P      NaN    NaN
10004        A  087  064   83  58  65   357    P      NaN    NaN
10005        A  059  045   50  35  48   237    P      NaN    NaN

In [90]:
sslc.loc[10001:10005]

        Region   fl   sl math sci sst total pass withheld  extra
Roll_no
10001        A  053  036   28  16  44   177  NaN      NaN    NaN
10002        A  058  037   42  35  40   212    P      NaN    NaN
10003        A  072  056   71  55  70   324    P      NaN    NaN
10004        A  087  064   83  58  65   357    P      NaN    NaN
10005        A  059  045   50  35  48   237    P      NaN    NaN

In [91]:
sslc.isnull().sum()

Region           0
fl               0
sl               0
math             0
sci              0
sst              0
total            0
pass         26595
withheld    185554
extra       185667
dtype: int64

In [92]:
sslc.describe(include = 'all')

,Region,fl,sl,math,sci,sst,total,pass,withheld,extra
count,185667,185667,185667,185667,185667,185667,185667.0,159072,113,0.0
unique,6,96,95,99,98,97,882.0,1,1,NaN
top,B,085,035,35,35,35,278.0,P,W,NaN
freq,41341,5989,6703,12842,25723,5334,592.0,159072,113,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
sslc['fl'].unique()

array(['053', '058', '072', '087', '059', '044', '062', '043', '049',
       '055', '048', '045', '083', '046', '037', '030', '050', '042',
       '067', '076', '074', '051', '056', '073', '071', '068', '069',
       '047', '064', '082', '079', '075', '086', '077', '054', '041',
       '078', '063', '084', '080', '085', '065', '090', '093', '092',
       '089', '081', '033', '070', '066', '060', '052', '034', '057',
       '021', '039', '036', '026', '032', '035', '040', '017', '027',
       '061', '024', '028', '088', '031', '029', '025', '038', '091',
       '094', '096', '095', '022', '019', '014', '016', '018', '023',
       '011', '012', '015', '004', '013', '010', '009', '020', '097',
       '006', '005', '007', '008', 'AA', '098'], dtype=object)

In [94]:
sslc['fl'].replace('AA', np.nan, inplace = True)
sslc['sst'].replace('AA', np.nan, inplace = True)
sslc['sl'].replace('AA', np.nan, inplace = True)
sslc['math'].replace('AA', np.nan, inplace = True)
sslc['sci'].replace('AA', np.nan, inplace = True)

<ipython-input-94-d904ba751471>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sslc['fl'].replace('AA', np.nan, inplace = True)
<ipython-input-94-d904ba751471>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sslc['sst'].replace('AA', np.nan, inplace = True)
<ipython-input-94-d904ba751471>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sslc['sl'].replace('AA', np.nan, inplace = True)
<ipython-input-94-d904ba751471>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sslc['math'].replace('AA', np.nan, inplace = True)
<ipython-input-94-d904ba751471>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sslc['sci'].replace('AA', np.nan, inplace = True)

In [95]:
sslc['fl'].info()

<class 'pandas.core.series.Series'>
Index: 185667 entries, 10001 to 199999
Series name: fl
Non-Null Count   Dtype
--------------   -----
185642 non-null  object
dtypes: object(1)
memory usage: 6.9+ MB

In [100]:
sslc['fl'] = pd.to_numeric(sslc['fl'], errors = 'coerce')
sslc['sst'] = pd.to_numeric(sslc['sst'], errors = 'coerce')
sslc['sl'] = pd.to_numeric(sslc['sl'], errors = 'coerce')
sslc['math'] = pd.to_numeric(sslc['math'], errors = 'coerce')
sslc['sci'] = pd.to_numeric(sslc['sci'], errors = 'coerce')
sslc['total'] = pd.to_numeric(sslc['total'], errors = 'coerce')

In [101]:
sslc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185667 entries, 10001 to 199999
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Region    185667 non-null  object
 1   fl        185642 non-null  float64
 2   sl        185532 non-null  float64
 3   math      185624 non-null  float64
 4   sci       185615 non-null  float64
 5   sst       185615 non-null  float64
 6   total     185666 non-null  float64
 7   pass      159072 non-null  object
 8   withheld  113 non-null     object
 9   extra     0 non-null       float64
dtypes: float64(7), object(3)
memory usage: 19.6+ MB

In [102]:
sslc['fl'].unique()

array([53., 58., 72., 87., 59., 44., 62., 43., 49., 55., 48., 45., 83.,
       46., 37., 30., 50., 42., 67., 76., 74., 51., 56., 73., 71., 68.,
       69., 47., 64., 82., 79., 75., 86., 77., 54., 41., 78., 63., 84.,
       80., 85., 65., 90., 93., 92., 89., 81., 33., 70., 66., 60., 52.,
       34., 57., 21., 39., 36., 26., 32., 35., 40., 17., 27., 61., 24.,
       28., 88., 31., 29., 25., 38., 91., 94., 96., 95., 22., 19., 14.,
       16., 18., 23., 11., 12., 15.,  4., 13., 10.,  9., 20., 97.,  6.,
        5.,  7.,  8., nan, 98.])

In [103]:
sslc.head()

        Region    fl    sl  math   sci   sst  total pass withheld  extra
Roll_no
10001        A  53.0  36.0  28.0  16.0  44.0  177.0  NaN      NaN    NaN
10002        A  58.0  37.0  42.0  35.0  40.0  212.0    P      NaN    NaN
10003        A  72.0  56.0  71.0  55.0  70.0  324.0    P      NaN    NaN
10004        A  87.0  64.0  83.0  58.0  65.0  357.0    P      NaN    NaN
10005        A  59.0  45.0  50.0  35.0  48.0  237.0    P      NaN    NaN